name: Rustlings Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
  outputFile:
    description: >
      outputFile used by custom script to compare and get grade.
    default: output.txt

  scriptPath:
    description: >
      default scripts path
    default: .github/classroom

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --test check --verbose
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: check_result
        path: ${{ github.workspace }}/.github/result/check_result.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm start






