name: Rustlings Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --test check --verbose
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: check_result
        path: ${{ github.workspace }}/.github/result
